// Simple localization utility for ScholarForge
export const translations = {
  en: {
    // Navigation
    learn: "Learn",
    dashboard: "Dashboard",
    community: "Community",
    create: "Create",
    wallet: "Wallet",
    profile: "Profile",
    
    // Course Completion
    courseCompleted: "Course Completed!",
    courseCompletedDesc: "You have successfully completed this course. Would you like to mint an NFT to record your achievement?",
    congratulations: "Congratulations",
    course: "Course",
    score: "Score",
    mintCompletionNFT: "Mint Completion NFT",
    autoProceedIn: "Auto-proceed in",
    skipAndContinue: "Skip & Continue to Quiz",
    mintingNFT: "Minting NFT...",
    pleaseWait: "Please wait while we record your completion on the blockchain",
    nftMintedSuccess: "NFT Minted Successfully",
    completionRecorded: "Your course completion has been recorded on the blockchain!",
    transactionHash: "Transaction Hash",
    proceedToQuiz: "Proceed to Quiz",
    connectWallet: "Please connect your wallet to mint NFT",
    mintingFailed: "Failed to mint NFT",
    
    // Learning
    chooseLanguage: "Choose Your Learning Language",
    selectLanguage: "Select the language you want to learn in",
    chooseTopic: "Choose Your Topic",
    learningIn: "Learning in",
    selectTopic: "Select what you want to learn about",
    backToLanguages: "← Back to Languages",
    startLearning: "Start Learning",
    
    // Topics
    culturalStudies: "Cultural Studies",
    culturalStudiesDesc: "Learn about African cultures and traditions",
    cryptoWeb3: "Cryptocurrency",
    cryptoWeb3Desc: "Blockchain, cryptocurrency, and digital finance",
    africanCuisine: "African Cuisine",
    africanCuisineDesc: "Traditional and modern African cooking",
    modernTechnology: "Modern Technology",
    modernTechnologyDesc: "Explore cutting-edge technology including AI and IoT",
    businessEntrepreneurship: "Business & Entrepreneurship",
    businessEntrepreneurshipDesc: "Business skills and startup knowledge",
    healthWellness: "Health & Wellness",
    healthWellnessDesc: "Learn about physical health and mental wellness",
    environmentalScience: "Environmental Science",
    environmentalScienceDesc: "Learn about conservation and sustainable living",
    
    // Course
    lessons: "lessons",
    progress: "Progress",
    markComplete: "Mark Complete",
    nextLesson: "Next Lesson",
    previousLesson: "← Previous Lesson",
    takeQuiz: "Take Quiz",
    
    // Quiz
    quizCompleted: "Quiz Completed!",
    greatJob: "Great job! You scored",
    and: "and",
    earned: "earned",
    goToDashboard: "Go to Dashboard",
    takeAnotherQuiz: "Take Another Quiz",
    
    // Create Lesson
    aiLessonCreator: "AI-Powered Lesson Creator",
    aiLessonCreatorDesc: "Generate culturally-relevant educational content with African context using advanced AI",
    createYourLesson: "Create Your Lesson",
    lessonLanguage: "Lesson Language",
    lessonTopic: "Lesson Topic",
    lessonTopicPlaceholder: "e.g., Introduction to Python programming, Blockchain applications for agriculture...",
    generateLesson: "Generate Lesson with AI",
    generating: "Generating",
    generatedLesson: "Generated Lesson",
    lessonContent: "Lesson Content",
    quiz: "Quiz",
    questions: "questions",
    publishLesson: "Publish Lesson",
    lessonPublished: "Lesson published successfully!",
    noLessonGenerated: "No lesson generated yet",
    generateLessonFirst: "Generate a lesson first to see it here",
    pleaseEnterTopic: "Please enter a lesson topic",
    failedToGenerate: "Failed to generate lesson. Please try again.",
    language: "Language",
    
    // Profile & Dashboard
    totalXP: "Total XP",
    level: "Level",
    dayStreak: "Day Streak",
    quizzes: "Quizzes",
    languages: "Languages",
    editProfile: "Edit Profile",
    saveProfile: "Save",
    learningProgress: "Learning Progress",
    achievements: "Achievements",
    recentActivity: "Recent Activity",
    
    // Blockchain
    mintXP: "Mint XP Tokens",
    mintSkillNFT: "Mint Skill NFT",
    wrongNetwork: "Wrong Network",
    switchNetwork: "Switch Network",
    connectWallet: "Connect your wallet to mint tokens",
    minting: "Minting...",
    mintingSuccess: "Minted Successfully!",
    mintingFailed: "Minting Failed",
    viewOnExplorer: "View on Explorer",
    connectedToEduChain: "Connected to EduChain Testnet",
    chainId: "Chain ID",
    network: "Network",
    wrongNetworkDetected: "Wrong Network Detected",
    current: "Current",
    required: "Required",
    switchToEduChain: "Switch to EduChain",
    xpBalance: "XP Balance",
    eduBalance: "EDU Balance",
    skillNFTs: "Skill NFTs",
    totalXPEarned: "Total XP Earned",
    
    // Common
    close: "Close",
    tryAgain: "Try Again",
    comingSoon: "Coming soon",
    loading: "Loading...",
    completed: "Completed",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    expert: "Expert"
  },
  
  tw: {
    // Navigation
    learn: "Kyerɛ",
    dashboard: "Dashboard",
    community: "Community",
    create: "Yɛ",
    wallet: "Wallet",
    profile: "Profile",
    
    // Course Completion
    courseCompleted: "Kyerɛ Awieɛ!",
    courseCompletedDesc: "Wo ayɛ kyerɛ yi yie. Wo pɛ sɛ wo yɛ NFT sɛ wo fa wo nneɛma a wo yɛɛ no nkyerɛ?",
    congratulations: "Yɛ adeɛ yie",
    course: "Kyerɛ",
    score: "Nkyerɛ",
    mintCompletionNFT: "Yɛ Completion NFT",
    autoProceedIn: "Auto-proceed wɔ",
    skipAndContinue: "Skip & Continue kɔ Quiz",
    mintingNFT: "Wɔ yɛ NFT...",
    pleaseWait: "Please wait sɛ yɛ fa wo completion nkyerɛ wɔ blockchain",
    nftMintedSuccess: "NFT Awieɛ Yie",
    completionRecorded: "Wo kyerɛ completion a wɔ fa nkyerɛ wɔ blockchain!",
    transactionHash: "Transaction Hash",
    proceedToQuiz: "Continue kɔ Quiz",
    connectWallet: "Fa wo wallet connect sɛ wo yɛ NFT",
    mintingFailed: "Wɔn yɛ NFT no",
    
    // Learning
    chooseLanguage: "Paw Wo Kyerɛ Kasa",
    selectLanguage: "Paw kasa a wo pɛ sɛ wo kyerɛ",
    chooseTopic: "Paw Wo Mmoa",
    learningIn: "Kyerɛ wɔ",
    selectTopic: "Paw biribi a wo pɛ sɛ wo kyerɛ",
    backToLanguages: "← San kɔ Kasa Ho",
    startLearning: "Fia Kyerɛ",
    
    // Topics
    culturalStudies: "Amanneɛ Kyerɛ",
    culturalStudiesDesc: "Kyerɛ amanneɛ ne amanaman a ɛwɔ Afrika",
    cryptoWeb3: "Crypto ne Web3",
    cryptoWeb3Desc: "Blockchain, cryptocurrency, ne sikasɛm a ɛwɔ digital",
    africanCuisine: "Aduan a ɛwɔ Afrika",
    africanCuisineDesc: "Aduan a ɛwɔ Afrika a ɛyɛ amanneɛ ne foforɔ",
    modernTechnology: "Teknoloji a Ɛwɔ Saa Bere Yi",
    modernTechnologyDesc: "Teknoloji a ɛwɔ saa bere yi, AI ne IoT",
    businessEntrepreneurship: "Adwumayɛ ne Sika Yɛ",
    businessEntrepreneurshipDesc: "Adwumayɛ nimdeɛ ne sika yɛ",
    healthWellness: "Yare ne Ahofadi",
    healthWellnessDesc: "Yare ne ahofadi a ɛwɔ Afrika",
    environmentalScience: "Nyansahu a Ɛfa Ho Yie",
    environmentalScienceDesc: "Nyansahu a ɛfa ho yie ne nneɛma a ɛwɔ Afrika",
    
    // Course
    lessons: "nsuahunu",
    progress: "Nkɔsoɔ",
    markComplete: "Fa Nkyerɛ Sɛ Ewieɛ",
    nextLesson: "Suaahunu A Eto Soɔ",
    previousLesson: "← Suaahunu A Ekan",
    takeQuiz: "Yɛ Quiz",
    
    // Quiz
    quizCompleted: "Quiz Awieɛ!",
    greatJob: "Yɛ adeɛ yie! Wo nyaa",
    and: "ne",
    earned: "wo nyaa",
    goToDashboard: "Kɔ Dashboard",
    takeAnotherQuiz: "Yɛ Quiz Foforɔ",
    
    // Create Lesson
    aiLessonCreator: "AI Suaahunu Yɛ",
    aiLessonCreatorDesc: "Yɛ kyerɛ a ɛwɔ amanneɛ a ɛwɔ Afrika a ɛfa AI ho",
    createYourLesson: "Yɛ Wo Suaahunu",
    lessonLanguage: "Suaahunu Kasa",
    lessonTopic: "Suaahunu Mmoa",
    lessonTopicPlaceholder: "e.g., Python programming kyerɛ, Blockchain a ɛfa kuayɛ ho...",
    generateLesson: "Yɛ Suaahunu fa AI ho",
    generating: "Wɔ yɛ",
    generatedLesson: "Suaahunu a Wɔ Yɛɛ",
    lessonContent: "Suaahunu Nneɛma",
    quiz: "Quiz",
    questions: "mbisa",
    publishLesson: "Fa Suaahunu Nkyerɛ",
    lessonPublished: "Suaahunu a wɔ yɛɛ no yie!",
    noLessonGenerated: "Wɔn yɛɛ suahunu biara da",
    generateLessonFirst: "Yɛ suahunu kan sɛ wo hwɛ wɔ ha",
    pleaseEnterTopic: "Fa suahunu mmoa bi kyerɛ",
    failedToGenerate: "Wɔn yɛɛ suahunu no. San yɛ bio.",
    language: "Kasa",
    
    // Profile & Dashboard
    totalXP: "XP Nyinaa",
    level: "Level",
    dayStreak: "Da A Wo Yɛɛ",
    quizzes: "Quizzes",
    languages: "Kasa",
    editProfile: "Sesa Profile",
    saveProfile: "Save",
    learningProgress: "Kyerɛ Nkɔsoɔ",
    achievements: "Nneɛma A Wo Yɛɛ",
    recentActivity: "Nneɛma A Wo Yɛɛ Nkyerɛ",
    
    // Blockchain
    mintXP: "Yɛ XP Tokens",
    mintSkillNFT: "Yɛ Skill NFT",
    wrongNetwork: "Network Nso",
    switchNetwork: "Sesa Network",
    connectWallet: "Fa wo wallet connect sɛ wo yɛ tokens",
    minting: "Wɔ yɛ...",
    mintingSuccess: "Awieɛ Yie!",
    mintingFailed: "Nso",
    viewOnExplorer: "Hwɛ wɔ Explorer",
    connectedToEduChain: "Connected kɔ EduChain Testnet",
    chainId: "Chain ID",
    network: "Network",
    wrongNetworkDetected: "Network Nso Wɔ Hwɛ",
    current: "Sɛn",
    required: "Sɛn",
    switchToEduChain: "Sesa kɔ EduChain",
    xpBalance: "XP Balance",
    eduBalance: "EDU Balance",
    skillNFTs: "Skill NFTs",
    totalXPEarned: "XP Nyinaa A Wo Nyaa",
    
    // Common
    close: "To",
    tryAgain: "San Yɛ Bio",
    comingSoon: "Reba",
    loading: "Wɔ load...",
    completed: "Awieɛ",
    beginner: "Foforɔ",
    intermediate: "Mfinimfini",
    advanced: "Advanced",
    expert: "Expert"
  },
  
  yo: {
    // Navigation
    learn: "Kọ",
    dashboard: "Dashboard",
    community: "Agbajo",
    create: "Dá",
    wallet: "Apamọ",
    profile: "Profaili",
    
    // Course Completion
    courseCompleted: "Ìkẹ́kọ̀ọ́ Parí!",
    courseCompletedDesc: "O ti parí ìkẹ́kọ̀ọ́ yìí ní ìṣe. Ṣe o fẹ́ dá NFT láti fi ìṣe rẹ sọ?",
    congratulations: "O dára",
    course: "Ìkẹ́kọ̀ọ́",
    score: "Ìdá",
    mintCompletionNFT: "Dá Completion NFT",
    autoProceedIn: "Auto-proceed nínú",
    skipAndContinue: "Skip & Continue sí Quiz",
    mintingNFT: "N dá NFT...",
    pleaseWait: "Jọ̀ọ́ dùró tí a fi ìparí rẹ sọ nínú blockchain",
    nftMintedSuccess: "NFT Dá Ní Onírúurú",
    completionRecorded: "Ìparí ìkẹ́kọ̀ọ́ rẹ ti fí sọ nínú blockchain!",
    transactionHash: "Transaction Hash",
    proceedToQuiz: "Continue sí Quiz",
    connectWallet: "Jọ̀ọ́ so apamọ rẹ mọ́ kí o lè dá NFT",
    mintingFailed: "Kò Dá NFT",
    
    // Learning
    chooseLanguage: "Yan Ede Tí O Fẹ́ Kọ́",
    selectLanguage: "Yan ede tí o fẹ́ kọ́",
    chooseTopic: "Yan Koko-ọrọ̀",
    learningIn: "Kíkọ́ nínú",
    selectTopic: "Yan ohun tí o fẹ́ kọ́",
    backToLanguages: "← Padà sí Ede",
    startLearning: "Bẹ̀rẹ̀ Kíkọ́",
    
    // Topics
    culturalStudies: "Ìkẹ́kọ̀ọ́ Àṣà",
    culturalStudiesDesc: "Kọ́ nípa àṣà àti ìṣe ilẹ̀ Adúláwọ̀",
    cryptoWeb3: "Crypto àti Web3",
    cryptoWeb3Desc: "Blockchain, cryptocurrency, àti owó digital",
    africanCuisine: "Oúnjẹ Ilẹ̀ Adúláwọ̀",
    africanCuisineDesc: "Oúnjẹ ilẹ̀ Adúláwọ̀ tí ó jẹ́ àṣà àti tuntun",
    modernTechnology: "Tẹ́knọ́lọ́jì Òde Òní",
    modernTechnologyDesc: "Tẹ́knọ́lọ́jì òde òní, AI àti IoT",
    businessEntrepreneurship: "Ìṣòwò àti Ìṣọ̀wọ́",
    businessEntrepreneurshipDesc: "Ìmọ̀ ìṣòwò àti ìmọ̀ bíbẹ̀rẹ̀",
    healthWellness: "Ìlera àti Ìgbọ́ràn",
    healthWellnessDesc: "Ìlera àti ìgbọ́ràn ilẹ̀ Adúláwọ̀",
    environmentalScience: "Ìjìnlẹ̀ Gbogboagbó",
    environmentalScienceDesc: "Ìjìnlẹ̀ gbogboagbó àti ìtọ́jú ayé",
    
    // Course
    lessons: "ìkẹ́kọ̀ọ́",
    progress: "Ìlọsíwájú",
    markComplete: "Fi Àmì Sí Iparí",
    nextLesson: "Ìkẹ́kọ̀ọ́ Tí O Tẹ́lé",
    previousLesson: "← Ìkẹ́kọ̀ọ́ Tí O Kọjá",
    takeQuiz: "Ṣe Quiz",
    
    // Quiz
    quizCompleted: "Quiz Parí!",
    greatJob: "Ṣe iṣẹ́ dára! O gba",
    and: "àti",
    earned: "o gba",
    goToDashboard: "Lọ sí Dashboard",
    takeAnotherQuiz: "Ṣe Quiz Mìíràn",
    
    // Create Lesson
    aiLessonCreator: "Olùkọ́ Ìkẹ́kọ̀ọ́ AI",
    aiLessonCreatorDesc: "Dá ìkẹ́kọ̀ọ́ tí ó ní àṣà ilẹ̀ Adúláwọ̀ pẹ̀lú AI",
    createYourLesson: "Dá Ìkẹ́kọ̀ọ́ Rẹ",
    lessonLanguage: "Ede Ìkẹ́kọ̀ọ́",
    lessonTopic: "Koko-ọrọ̀ Ìkẹ́kọ̀ọ́",
    lessonTopicPlaceholder: "e.g., Ìkẹ́kọ̀ọ́ Python, Blockchain fún àgbẹ̀...",
    generateLesson: "Dá Ìkẹ́kọ̀ọ́ pẹ̀lú AI",
    generating: "N dá",
    generatedLesson: "Ìkẹ́kọ̀ọ́ Tí A Dá",
    lessonContent: "Àkọsílẹ̀ Ìkẹ́kọ̀ọ́",
    quiz: "Quiz",
    questions: "ìbéèrè",
    publishLesson: "Tẹ́ Ìkẹ́kọ̀ọ́",
    lessonPublished: "Ìkẹ́kọ̀ọ́ tẹ́ sílẹ̀!",
    noLessonGenerated: "A kò dá ìkẹ́kọ̀ọ́ kankan",
    generateLessonFirst: "Dá ìkẹ́kọ̀ọ́ kan kí o rí i níbí",
    pleaseEnterTopic: "Jọ̀ọ́ fi koko-ọrọ̀ ìkẹ́kọ̀ọ́ kan sọ",
    failedToGenerate: "Kò dá ìkẹ́kọ̀ọ́. Gbìyànjú lẹ́ẹ̀kan si.",
    language: "Ede",
    
    // Profile & Dashboard
    totalXP: "XP Gbogbo",
    level: "Ipele",
    dayStreak: "Ọjọ́ Tí O Ṣe",
    quizzes: "Quizzes",
    languages: "Ede",
    editProfile: "Ṣàtúnṣe Profaili",
    saveProfile: "Fi",
    learningProgress: "Ìlọsíwájú Ìkẹ́kọ̀ọ́",
    achievements: "Ìṣẹ́gun",
    recentActivity: "Ìṣẹ́ Tí O Ṣe Látíjọ́",
    
    // Blockchain
    mintXP: "Dá XP Tokens",
    mintSkillNFT: "Dá Skill NFT",
    wrongNetwork: "Nẹ́tiwọọ̀kì Kò Tọ́",
    switchNetwork: "Yípadà Nẹ́tiwọọ̀kì",
    connectWallet: "So apamọ rẹ mọ́ kí o lè dá tokens",
    minting: "N dára...",
    mintingSuccess: "Dá Ní Onírúurú!",
    mintingFailed: "Kò Dá",
    viewOnExplorer: "Wo lórí Explorer",
    connectedToEduChain: "Ti so mọ́ EduChain Testnet",
    chainId: "Chain ID",
    network: "Nẹ́tiwọọ̀kì",
    wrongNetworkDetected: "A Rí Nẹ́tiwọọ̀kì Tí Kò Tọ́",
    current: "Lọ́wọ́lọ́wọ́",
    required: "Tí A Fẹ́",
    switchToEduChain: "Yípadà Sí EduChain",
    xpBalance: "XP Balance",
    eduBalance: "EDU Balance",
    skillNFTs: "Skill NFTs",
    totalXPEarned: "XP Gbogbo Tí O Gba",
    
    // Common
    close: "Pí",
    tryAgain: "Gbìyànjú Lẹ́ẹ̀kan Si",
    comingSoon: "N bọ̀",
    loading: "N gbé...",
    completed: "Parí",
    beginner: "Olùbẹ̀rẹ̀",
    intermediate: "Alágbàgbé",
    advanced: "Olùgbà",
    expert: "Olùgbà"
  },
  
  sw: {
    // Navigation
    learn: "Jifunze",
    dashboard: "Dashibodi",
    community: "Jamii",
    create: "Tengeneza",
    wallet: "Pochi",
    profile: "Wasifu",
    
    // Course Completion
    courseCompleted: "Somo Limekamilika!",
    courseCompletedDesc: "Umekamilisha somo hili kwa mafanikio. Je, ungependa kutengeneza NFT ili kurekodi mafanikio yako?",
    congratulations: "Hongera",
    course: "Somo",
    score: "Alama",
    mintCompletionNFT: "Tengeneza Completion NFT",
    autoProceedIn: "Auto-proceed katika",
    skipAndContinue: "Ruka & Endelea kwa Jaribio",
    mintingNFT: "Inatengeneza NFT...",
    pleaseWait: "Tafadhali subiri tunaporekodi ukamilishaji wako kwenye blockchain",
    nftMintedSuccess: "NFT Imeongenezwa Kwa Ufanisi",
    completionRecorded: "Ukamilishaji wako wa somo umeongezwa kwenye blockchain!",
    transactionHash: "Transaction Hash",
    proceedToQuiz: "Endelea kwa Jaribio",
    connectWallet: "Tafadhali unganisha pochi yako ili kutengeneza NFT",
    mintingFailed: "Imeshindwa Kutengeneza NFT",
    
    // Learning
    chooseLanguage: "Chagua Lugha Yako ya Kujifunza",
    selectLanguage: "Chagua lugha unayotaka kujifunza",
    chooseTopic: "Chagua Mada Yako",
    learningIn: "Kujifunza kwa",
    selectTopic: "Chagua unachotaka kujifunza",
    backToLanguages: "← Rudi kwa Lugha",
    startLearning: "Anza Kujifunza",
    
    // Topics
    culturalStudies: "Masomo ya Utamaduni",
    culturalStudiesDesc: "Jifunze kuhusu utamaduni wa Kiafrika na mila",
    cryptoWeb3: "Crypto na Web3",
    cryptoWeb3Desc: "Blockchain, cryptocurrency, na fedha za kidijitali",
    africanCuisine: "Chakula cha Kiafrika",
    africanCuisineDesc: "Chakula cha Kiafrika cha kitamaduni na cha kisasa",
    modernTechnology: "Teknolojia ya Kisasa",
    modernTechnologyDesc: "Teknolojia ya kisasa pamoja na AI na IoT",
    businessEntrepreneurship: "Biashara na Ujasiriamali",
    businessEntrepreneurshipDesc: "Ujuzi wa biashara na ujasiriamali",
    healthWellness: "Afya na Ustawi",
    healthWellnessDesc: "Afya na ustawi wa Kiafrika",
    environmentalScience: "Sayansi ya Mazingira",
    environmentalScienceDesc: "Sayansi ya mazingira na uhifadhi",
    
    // Course
    lessons: "masomo",
    progress: "Maendeleo",
    markComplete: "Weka Alama ya Kumaliza",
    nextLesson: "Somo Lijalo",
    previousLesson: "← Somo la Awali",
    takeQuiz: "Fanya Jaribio",
    
    // Quiz
    quizCompleted: "Jaribio Limekamilika!",
    greatJob: "Vizuri sana! Umepata alama",
    and: "na",
    earned: "umepata",
    goToDashboard: "Nenda Dashibodi",
    takeAnotherQuiz: "Fanya Jaribio Lingine",
    
    // Create Lesson
    aiLessonCreator: "Mjenzi wa Masomo ya AI",
    aiLessonCreatorDesc: "Tengeneza maudhui ya elimu yenye muktadha wa Kiafrika kwa kutumia AI",
    createYourLesson: "Tengeneza Somo Lako",
    lessonLanguage: "Lugha ya Somo",
    lessonTopic: "Mada ya Somo",
    lessonTopicPlaceholder: "e.g., Utangulizi wa Python, Matumizi ya Blockchain kwa kilimo...",
    generateLesson: "Tengeneza Somo kwa AI",
    generating: "Inatengeneza",
    generatedLesson: "Somo Lililotengenezwa",
    lessonContent: "Maudhui ya Somo",
    quiz: "Jaribio",
    questions: "maswali",
    publishLesson: "Chapisha Somo",
    lessonPublished: "Somo limechapishwa kwa mafanikio!",
    noLessonGenerated: "Hakuna somo lililotengenezwa bado",
    generateLessonFirst: "Tengeneza somo kwanza ili ulione hapa",
    pleaseEnterTopic: "Tafadhali weka mada ya somo",
    failedToGenerate: "Imeshindwa kutengeneza somo. Jaribu tena.",
    language: "Lugha",
    
    // Profile & Dashboard
    totalXP: "Jumla ya XP",
    level: "Kiwango",
    dayStreak: "Mfululizo wa Siku",
    quizzes: "Majaribio",
    languages: "Lugha",
    editProfile: "Hariri Wasifu",
    saveProfile: "Hifadhi",
    learningProgress: "Maendeleo ya Kujifunza",
    achievements: "Mafanikio",
    recentActivity: "Shughuli za Hivi Karibuni",
    
    // Blockchain
    mintXP: "Tengeneza Tokeni za XP",
    mintSkillNFT: "Tengeneza NFT ya Ujuzi",
    wrongNetwork: "Mtandao Usio Sahihi",
    switchNetwork: "Badilisha Mtandao",
    connectWallet: "Unganisha pochi yako ili kutengeneza tokeni",
    minting: "Inaengeneza...",
    mintingSuccess: "Imetengenezwa Kwa Ufanisi!",
    mintingFailed: "Imeshindwa Kutengeneza",
    viewOnExplorer: "Angalia kwenye Explorer",
    connectedToEduChain: "Imeunganishwa na EduChain Testnet",
    chainId: "Chain ID",
    network: "Mtandao",
    wrongNetworkDetected: "Mtandao Usio Sahihi Uligunduliwa",
    current: "Sasa",
    required: "Inahitajika",
    switchToEduChain: "Badilisha kwa EduChain",
    xpBalance: "Jumla ya XP",
    eduBalance: "Jumla ya EDU",
    skillNFTs: "NFT za Ujuzi",
    totalXPEarned: "XP Zote Zilizopatikana",
    
    // Common
    close: "Funga",
    tryAgain: "Jaribu Tena",
    comingSoon: "Inakuja hivi karibuni",
    loading: "Inapakia...",
    completed: "Imekamilika",
    beginner: "Mwanzo",
    intermediate: "Kati",
    advanced: "Juu",
    expert: "Mtaalamu"
  }
};

export const getTranslation = (key, languageCode = 'en') => {
  return translations[languageCode]?.[key] || translations.en[key] || key;
};

export const getCurrentLanguage = () => {
  try {
    return localStorage.getItem('sf_selected_language_code') || 'en';
  } catch {
    return 'en';
  }
};

export const t = (key) => {
  return getTranslation(key, getCurrentLanguage());
};
